# Basic Information 
title: Xin Tong
position: Assistant Professor
department: CACSO
department_link: https://cacso.nju.edu.cn/main.psp
affiliation: Nanjing University
affiliation_link: https://www.nju.edu.cn
affiliation_logo: ./assets/img/nju_logo.png
email: xintong (at) nju.edu.cn

# Search Engine Optimization (SEO)
keywords: xin tong, tong xin, xintong, tongxin
canonical: https://cacso.nju.edu.cn/main.psp
description: Xin Tong is an assistant professor at Nanjing University. 

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: true

# Links
link_type: icon #text/icon
# google_scholar: https://scholar.google.com/citations?user=Qi2PSmEAAAAJ
# github_link: https://github.com/yaoyao-liu/
# linkedin: https://www.linkedin.com/in/liuyaoyao/
# twitter: https://twitter.com/YaoyaoLiu1/
orcid: https://orcid.org/0000-0002-6646-0638

# Images 
avatar: ./assets/img/TongXin_Photo_202208.jpg  # base: https://img.yliu.me/avatar.jpg 
favicon: ./assets/img/nju_favicon.ico
favicon_dark: ./assets/img/nju_favicon.ico

# Footnotes
footnote: Powered by Jekyll and Minimal Light theme.
footnote_link: https://github.com/yaoyao-liu/yaoyao-liu.github.io

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# clustrmaps_id: CJD8XwsJhSyQ6sbsU-Gw0cNcUlbah7KW3xvHN2QlwW0

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
